### ISSUE TITLE
Update the filtering capabilities of the select kafka instances step

### ISSUE THREAD

**Issue by riccardo-forina** [bf2fc6cc711aee1a0c2a/cos-ui#14]
At the moment it's possible to search by name and filter by status. We should also be able to filter by cloud provider, region, and owner. 
![image](https://user-images.githubusercontent.com/966316/121490257-23286900-c9d5-11eb-840d-d1aaf43a447a.png)

The design of the toolbar seems to follow the [PF HTML demos](https://www.patternfly.org/v4/components/toolbar/html-demos), but the [React demo](https://www.patternfly.org/v4/components/toolbar/react-demos) and [the Toolbar docs](https://www.patternfly.org/v4/components/toolbar) don't show how to achieve that. We need to figure that out.

### Tasks
- [ ] add the cloud provider filter
- [ ] add the region filter
- [ ] add the owner filter
- [ ] update the toolbar design to match the HTML demos
